spring.application.name=SkyShopServer
server.address=0.0.0.0
server.port=443
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=${SSL_PASSWORD}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=borislove